Forgot to commit serialization util
This serialization improvement fixes
RuntimeError: tensors are on different GPUs
when model is trained and evaluated on different devices